### PR TITLE
add Mac OSX defines and installation paths

### PR DESCRIPTION
**Pull request by keinkurt**
related to #43

### CODE REVIEW

**Comment by martinrotter** [comment]
This makes RSS Guard compilable on OS X right?

From first sight it seems that the paths are not totally correct for Mac OS X? Because I thought you have some "bundle" format. I thought that applications in OS X should follow [this layout](https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html). Correct me if I am wrong.

For me, this PR is fine. Do just one tweak pls. Leave the original section
```
# Install files on Linux only.
unix:!mac {
........
}
```
intact and add completely new section `unix:mac`. Do not split the original `unix:!mac` sections. I would like to have all those "install" sections completely exclusive and separate.

**Comment by martinrotter** [comment]
Also check [this](https://github.com/QuiteRSS/quiterss/blob/master/QuiteRSS.pro#L316). It is PRO file from one of competing applications of RSS Guard. They use the same approach as we should use. Check out their `mac` section. They are clearly installing application resource files to `Contents/Resources` subfolder, thus they are using "bundles" too.

**Comment by martinrotter** [comment]
So we would also need files:
* QMAKE_INFO_PLIST = Info.plist
* ICON = quiterss.icns

**Comment by martinrotter** [comment]
I tried to run OS X in VirtualBox (niresh) but did not suceeded, perhaps you can give me some working tutorial on how to do it. In that case, I could help.

**Comment by martinrotter** [comment]
So let me know if you will tweak the PR or I can add some blind tweaks by myself and it will maybe work.

**Comment by keinkurt** [comment]
I'm working on it and will tweak this PR.

**Comment by martinrotter** [comment]
Okay, perfectos.

**Comment by martinrotter** [comment]
BTW, note there are some macosx files in `resources/macosx` folder. Icon and plist, feel free to edit/replace them.

**Comment by keinkurt** [comment]
Now it should be better. There is still one problem of missing the app icon, but unfortunately I don't have experiences in compiling OSX apps. Maybe someone else can fix it.

**Comment by keinkurt** [comment]
Within the last commit, I'm using the Files under resources/macosx.

**Comment by martinrotter** [comment]
This is better, still `definitions.h` file's paths do not match paths in the bundle, but I will merge this, looks reasonable.

So you managed to produce bundle file? Is it `.dmg` file?

**Comment by keinkurt** [comment]
No it's not a .dmg file, it's only a .app directory/file/bundle, which you can start the application at Finder.

**Comment by martinrotter** [comment]
Yes, but you can pack it into single dmg file right? See [here, bottom](http://doc.qt.io/qt-5/osx-deployment.html).

**Comment by martinrotter** [comment]
`-dmg	Create a .dmg disk image`

**Pull request merged**
