### PR TITLE
Solution bug #172

### PR DESCRIPTION
**Pull request by fanteik**
Hello,

I’ve fixed Bug #172 in the branch named “tt-rss/dateError” in my fork.
Unfortunately with this bug one can't use rssguard together with tiny tiny rss. I hope this will help to get rid of it.

Thanx

### CODE REVIEW

**Comment by martinrotter** [comment]
Thank you very much, bug was really there. :)

**Comment by jluttine** [comment]
I'm experiencing this bug. A new release with this fix would be great.

**Comment by martinrotter** [comment]
OK, I will review current state of [master] and release today. :) Thank you for pointing this out, I am quite busy these months with my life issues etc.

**Comment by jluttine** [comment]
Yeah, no worries. Thanks a lot!

**Comment by jluttine** [comment]
Just confirming that this indeed fixed the bug. Thanks! :+1:

**Pull request merged**
