### PR TITLE
Port build system to CMake

### PR DESCRIPTION
**Pull request by CyberTailor**
**Rationale:**  
CMake is the preferred build system for Qt now, also it's more flexible.

**TODO:**  
Fix rssguard.rc file (RC compiler throws error 2135).

**Builds:**  
https://github.com/CyberTailor/rssguard/releases/tag/devbuild

### CODE REVIEW

**Comment by martinrotter** [comment]
Hello @CyberTailor.

Nice PR right there. This is obviously quite a big change. Several questions:

1. `CMake is the preferred build system for Qt now, also it's more flexible.` Where did you get that info from? AFAIK `cmake` is not really preferred build system for Qt apps, only for Qt libs themselves.
2. Did you test the change with both Qt 5 and Qt 6?

Personally, I like `qmake` for its simplicity and clean syntax. It does exactly what I want it to do. At this point, transition to `cmake` is not probably needed, but in future it will be probably needed, indeed.

**Comment by martinrotter** [comment]
Anway, your code looks very nice and I was able to understand it fine. Merging and will improve, feel free to post any followup PRs if I screws something up.

**Comment by martinrotter** [comment]
Working on that cmake RN, some fixups and things I prefer. Thanks bro.

**Comment by martinrotter** [comment]
@CyberTailor I have a problem.

When successfully building rssguard and changing one CPP (not header, just a source) file, cmake always rebuilds half of the project even when it should just recompile the changed file.

Ninja explain spits out crazy number of "dirty" stuff, when actually non of that changed since last build, only the file "feedmessageviewer.cpp" was altered this time to trigger the problem:

```
C:\Projekty\Moje\build-rssguard-Desktop_Qt_6_2_3_MSVC2017_64bit-Debug>ninja -d explain -v
ninja explain: restat of output src/librssguard/rssguard_autogen/timestamp older than most recent input C:/Projekty/Moje/rssguard/src/librssguard/gui/feedmessageviewer.cpp (6654105835809379 vs 6654108449767150)
ninja explain: C:/Projekty/Moje/build-rssguard-Desktop_Qt_6_2_3_MSVC2017_64bit-Debug/src/librssguard/rssguard_autogen/mocs_compilation.cpp is dirty
ninja explain: src/librssguard/rssguard_autogen/timestamp is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_adblockdialog.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_authenticationdetails.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_downloaditem.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_downloadmanager.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_feedlyaccountdetails.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_formabout.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_formaccountdetails.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_formaddaccount.h is dirty
ninja explain: src/librssguard/rssguard_autogen/include/ui_formaddeditemail.h is dirty
```

Any ideas?

**Comment by CyberTailor** [comment]
> When successfully building rssguard and changing one CPP (not header, just a source) file, cmake always rebuilds half of the project even when it should just recompile the changed file.

Couldn't reproduce:

```
ninja explain: output localization/all of phony edge with no inputs doesn't exist
ninja explain: localization/all is dirty
ninja explain: restat of output src/librssguard/rssguard_autogen/timestamp older than most recent input ../src/librssguard/gui/feedmessageviewer.cpp (1643710298815242342 vs 1643710322467066132)
ninja explain: /home/cyber/@CLONE/rssguard/build/src/librssguard/rssguard_autogen/mocs_compilation.cpp is dirty
ninja explain: /home/cyber/@CLONE/rssguard/build/src/librssguard/rssguard_autogen/mocs_compilation.cpp is dirty
ninja explain: src/librssguard/rssguard_autogen/timestamp is dirty
ninja explain: src/librssguard/CMakeFiles/rssguard_autogen is dirty
ninja explain: src/librssguard/rssguard_autogen/timestamp is dirty
ninja explain: src/librssguard/rssguard_autogen/mocs_compilation.cpp is dirty
ninja explain: src/librssguard/CMakeFiles/rssguard.dir/rssguard_autogen/mocs_compilation.cpp.o is dirty
ninja explain: output src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o older than most recent input /home/cyber/@CLONE/rssguard/src/librssguard/gui/feedmessageviewer.cpp (1643710303771995843 vs 1643710322467066132)
ninja explain: src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o is dirty
ninja explain: src/librssguard/librssguard.so is dirty
ninja explain: src/librssguard/all is dirty
ninja explain: src/librssguard/librssguard.so is dirty
ninja explain: src/rssguard/CMakeFiles/app_autogen_timestamp_deps is dirty
ninja explain: src/librssguard/librssguard.so is dirty
ninja explain: src/rssguard/app_autogen_timestamp_deps is dirty
ninja explain: src/librssguard/librssguard.so is dirty
ninja explain: src/rssguard/rssguard is dirty
ninja explain: src/rssguard/all is dirty
[1/5] cd /home/cyber/@CLONE/rssguard/build/src/librssguard && /usr/bin/cmake -E cmake_autogen /home/cyber/@CLONE/rssguard/build/src/librssguard/CMakeFiles/rssguard_autogen.dir/AutogenInfo.json Release && /usr/bin/cmake -E touch /home/cyber/@CLONE/rssguard/build/src/librssguard/rssguard_autogen/timestamp && /usr/bin/cmake -E cmake_transform_depfile Ninja gccdepfile /home/cyber/@CLONE/rssguard /home/cyber/@CLONE/rssguard/src/librssguard /home/cyber/@CLONE/rssguard/build /home/cyber/@CLONE/rssguard/build/src/librssguard /home/cyber/@CLONE/rssguard/build/src/librssguard/rssguard_autogen/deps /home/cyber/@CLONE/rssguard/build/CMakeFiles/d/46e380c3c6a71f44d0f2da714da0b0f56745d9665607ef9f3d07aaf98b2299ca.d
[2/4] /usr/bin/ccache  c++ -DAPP_AUTHOR="\"Martin Rotter\"" -DAPP_DONATE_URL=\"https://github.com/sponsors/martinrotter\" -DAPP_EMAIL=\"rotter.martinos@gmail.com\" -DAPP_LONG_NAME="\"RSS Guard 4.2.0\"" -DAPP_LOW_H_NAME=\".rssguard\" -DAPP_LOW_NAME=\"rssguard\" -DAPP_NAME="\"RSS Guard\"" -DAPP_REVISION=\"a01ae489-nowebengine\" -DAPP_SYSTEM_NAME=\"Linux\" -DAPP_SYSTEM_VERSION=\"x86_64\" -DAPP_URL=\"https://github.com/martinrotter/rssguard\" -DAPP_URL_DOCUMENTATION=\"https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md\" -DAPP_URL_ISSUES=\"https://github.com/martinrotter/rssguard/issues\" -DAPP_URL_ISSUES_NEW=\"https://github.com/martinrotter/rssguard/issues/new\" -DAPP_USERAGENT="\"RSS Guard/4.2.0\"" -DAPP_VERSION=\"4.2.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_SQL_LIB -DQT_USE_FAST_CONCATENATION -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DRSSGUARD_DLLSPEC=Q_DECL_EXPORT -DUNICODE -D_UNICODE -Drssguard_EXPORTS -I/home/cyber/@CLONE/rssguard/build/src/librssguard -I/home/cyber/@CLONE/rssguard/src/librssguard -I/home/cyber/@CLONE/rssguard/build/src/librssguard/rssguard_autogen/include -I/home/cyber/@CLONE/rssguard/src/librssguard/gui -I/home/cyber/@CLONE/rssguard/src/librssguard/gui/dialogs -I/home/cyber/@CLONE/rssguard/src/librssguard/gui/reusable -I/home/cyber/@CLONE/rssguard/src/librssguard/dynamic-shortcuts -I/home/cyber/@CLONE/rssguard/src/librssguard/gui/notifications -I/home/cyber/@CLONE/rssguard/src/librssguard/gui/toolbars -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtDBus -O3 -DNDEBUG -fPIC -fPIC -std=gnu++17 -MD -MT src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o -MF src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o.d -o src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o -c '/home/cyber/@CLONE/rssguard/src/librssguard/gui/feedmessageviewer.cpp'
[3/4] : && /usr/bin/ccache  c++ -fPIC -O3 -DNDEBUG   -shared -Wl,-soname,librssguard.so -o src/librssguard/librssguard.so src/librssguard/CMakeFiles/rssguard.dir/rssguard_autogen/mocs_compilation.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/feeddownloader.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/feedsmodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/feedsproxymodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/filterutils.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/message.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagefilter.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messageobject.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagesforfiltersmodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagesmodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagesmodelcache.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagesmodelsqllayer.cpp.o src/librssguard/CMakeFiles/rssguard.dir/core/messagesproxymodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/databasecleaner.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/databasedriver.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/databasefactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/databasequeries.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/mariadbdriver.cpp.o src/librssguard/CMakeFiles/rssguard.dir/database/sqlitedriver.cpp.o src/librssguard/CMakeFiles/rssguard.dir/dynamic-shortcuts/dynamicshortcuts.cpp.o src/librssguard/CMakeFiles/rssguard.dir/dynamic-shortcuts/dynamicshortcutswidget.cpp.o src/librssguard/CMakeFiles/rssguard.dir/dynamic-shortcuts/shortcutcatcher.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/applicationexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/feedfetchexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/filteringexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/ioexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/networkexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/exceptions/scriptexception.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formabout.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formaddaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formaddeditlabel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formbackupdatabasesettings.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formdatabasecleanup.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formmain.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formmessagefiltersmanager.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formrestoredatabasesettings.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formsettings.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/dialogs/formupdate.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/feedmessageviewer.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/feedsview.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/guiutilities.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/messagebox.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/messagepreviewer.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/messagesview.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/newspaperpreviewer.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/notifications/notificationseditor.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/notifications/singlenotificationeditor.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/baselineedit.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/basetreeview.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/colortoolbutton.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/comboboxwithstatus.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/edittableview.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/helpspoiler.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/labelsmenu.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/labelwithstatus.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/lineeditwithstatus.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/messagecountspinbox.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/networkproxydetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/nonclosablemenu.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/plaintoolbutton.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/progressbarwithtext.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/resizablestackedwidget.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/searchtextwidget.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/squeezelabel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/styleditemdelegatewithoutfocus.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/timespinbox.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/treeviewcolumnsmenu.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/reusable/widgetwithstatus.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsbrowsermail.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsdatabase.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsdownloads.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsfeedsmessages.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsgeneral.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsgui.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingslocalization.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsnodejs.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsnotifications.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingspanel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/settings/settingsshortcuts.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/systemtrayicon.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/tabbar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/tabcontent.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/tabwidget.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/toolbars/basetoolbar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/toolbars/feedstoolbar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/toolbars/messagestoolbar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/toolbars/statusbar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/toolbars/toolbareditor.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/application.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/autosaver.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/externaltool.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/feedreader.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/iconfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/iofactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/localization.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/mutex.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/nodejs.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/notification.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/notificationfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/regexfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/settings.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/singleapplication.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/skinfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/systemfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/miscellaneous/textfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/basenetworkaccessmanager.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/cookiejar.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/downloader.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/downloadmanager.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/httpresponse.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/networkfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/oauth2service.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/oauthhttphandler.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/silentnetworkaccessmanager.cpp.o src/librssguard/CMakeFiles/rssguard.dir/network-web/webfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/accountcheckmodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/cacheforserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/category.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/feed.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/gui/authenticationdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/gui/formaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/gui/formcategorydetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/gui/formfeeddetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/importantnode.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/label.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/labelsnode.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/recyclebin.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/rootitem.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/serviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/abstract/unreadnode.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/feedly/feedlyentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/feedly/feedlynetwork.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/feedly/feedlyserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/feedly/gui/feedlyaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/feedly/gui/formeditfeedlyaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gmailentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gmailnetworkfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gmailserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gui/emailrecipientcontrol.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gui/formaddeditemail.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gui/formdownloadattachment.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gui/formeditgmailaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/gmail/gui/gmailaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/greader/greaderentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/greader/greadernetwork.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/greader/greaderserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/greader/gui/formeditgreaderaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/greader/gui/greaderaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/gui/formeditowncloudaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/gui/owncloudaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/owncloudfeed.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/owncloudnetworkfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/owncloudserviceentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/owncloud/owncloudserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/gui/formeditredditaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/gui/redditaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/redditcategory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/redditentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/redditnetworkfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/redditserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/reddit/redditsubscription.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/atomparser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/feedparser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/gui/formeditstandardaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/gui/formstandardfeeddetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/gui/formstandardimportexport.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/gui/standardfeeddetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/jsonparser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/rdfparser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/rssparser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/standardcategory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/standardfeed.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/standardfeedsimportexportmodel.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/standardserviceentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/standard/standardserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/gui/formeditttrssaccount.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/gui/formttrssfeeddetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/gui/formttrssnote.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/gui/ttrssaccountdetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/gui/ttrssfeeddetails.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/ttrssfeed.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/ttrssnetworkfactory.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/ttrssserviceentrypoint.cpp.o src/librssguard/CMakeFiles/rssguard.dir/services/tt-rss/ttrssserviceroot.cpp.o src/librssguard/CMakeFiles/rssguard.dir/3rd-party/mimesis/mimesis.cpp.o src/librssguard/CMakeFiles/rssguard.dir/3rd-party/mimesis/quoted-printable.cpp.o src/librssguard/CMakeFiles/rssguard.dir/3rd-party/sc/simplecrypt.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/messagetextbrowser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/gui/messagebrowser.cpp.o src/librssguard/CMakeFiles/rssguard.dir/qrc_sql.cpp.o src/librssguard/CMakeFiles/rssguard.dir/qrc_rssguard.cpp.o  /usr/lib64/libQt5Qml.so.5.15.2  /usr/lib64/libQt5Sql.so.5.15.2  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libQt5Multimedia.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5DBus.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2 && :
[4/4] : && /usr/bin/ccache  c++ -O3 -DNDEBUG  src/rssguard/CMakeFiles/app.dir/app_autogen/mocs_compilation.cpp.o src/rssguard/CMakeFiles/app.dir/main.cpp.o -o src/rssguard/rssguard  -Wl,-rpath,/home/cyber/@CLONE/rssguard/build/src/librssguard:  src/librssguard/librssguard.so  /usr/lib64/libQt5Widgets.so.5.15.2  /usr/lib64/libQt5Qml.so.5.15.2  /usr/lib64/libQt5Sql.so.5.15.2  /usr/lib64/libQt5Xml.so.5.15.2  /usr/lib64/libQt5Multimedia.so.5.15.2  /usr/lib64/libQt5Gui.so.5.15.2  /usr/lib64/libQt5Network.so.5.15.2  /usr/lib64/libQt5DBus.so.5.15.2  /usr/lib64/libQt5Core.so.5.15.2 && :
```

**Comment by martinrotter** [comment]
I already pushed a potential fix. The issue clearly does not show on all platforms. Also, it could be related to the actual version of cmake? Not sure.

**Comment by martinrotter** [comment]
Anway, this is better since now "UI" file also show in IDE project structure, before, they did not.

**Comment by martinrotter** [comment]
Discovered another problem, Qt 5.12.9 does not build, fails with 

```
target_link_libraries(rssguard PUBLIC
  Qt::Core
  Qt::Gui
  Qt::Network
  Qt::Qml
  Qt::Sql
  Qt::Widgets
  Qt::Xml
)
```

being the problem as clearly "Qt5::Core" (etc) is expected.

**Comment by martinrotter** [comment]
> Discovered another problem, Qt 5.12.9 does not build, fails with
> 
> ```
> target_link_libraries(rssguard PUBLIC
>   Qt::Core
>   Qt::Gui
>   Qt::Network
>   Qt::Qml
>   Qt::Sql
>   Qt::Widgets
>   Qt::Xml
> )
> ```
> 
> being the problem as clearly "Qt5::Core" (etc) is expected.
> 
> https://doc.qt.io/qt-5/cmake-get-started.html#imported-library-targets

Fixing.

**Comment by martinrotter** [comment]
8fa0a3a72

**Pull request merged**
