### PR TITLE
add feed option to load article URL in message preview

### PR DESCRIPTION
**Pull request by igrekster**
Some RSS feeds (such as reddit.com) provide quite limited `content`
section, thus it is desirable to load the URL into the message preview.

### CODE REVIEW

**Comment by igrekster** [comment]
Hey @martinrotter, I'm new to the project -- feel free to suggest any refactoring for this PR.

Here is a screenshot of the option:
Screenshot_20220116_181808

**Comment by martinrotter** [comment]
Hello @igrekster.

What a cure PR you provided! This is actually one of the first PRs in this project which actually add some new substantial feature. Thank you for that.

1. Indeed, that feature was requested before.
2. Your PR is implemented very well, and could be merged as is and "would" work.
3. The only and quite big problem I have is that this feature is (should be) actually universal. It should not work just for "standard" feeds, but for all feeds from all plugins (Inoreader, Nextcloud etc.), because those feeds offer articles with URLs too.

Now, to expand. For all features, which are not plugin-specific (are universal), I do not usually use `Feed::setCustomDatabaseData` function to store the data, but I use the DB "Feeds" table directly, because the data is universal at that point.

So, better approach requires creating of new set of SQL files (which will create new column into both SQLite and MariaDB backends), bumping SQL "version" number, testing those new SQLs, moving new UI into `services/abstract/gui/formfeeddetails.ui` and that's it. Would you be able to do it, or should I?

**Comment by igrekster** [comment]
Hi @martinrotter,
thank you very much for the detailed response -- appreciate it.

>  Would you be able to do it, or should I?

I gave it a go, apart from bumping the schema version and creating a new `db_update_%1_%2_%3.sql` - I'm not entirely clear on this part.
Feel free to take over or add the necessary changes.

**Comment by martinrotter** [comment]
OK, I will merge your PR and build upon it tomorrow perhaps. Thanks man.

**Comment by igrekster** [comment]
One issue with merging it as is is that it won't start if there is a database already as it would be missing the field.

**Comment by AmmarSaleemG** [comment]
@martinrotter this change has not yet created in [Development Builds](https://github.com/martinrotter/rssguard/releases/tag/devbuild). Please do it

**Comment by martinrotter** [comment]
WAIT jesus christ. I am fixing the PR.

**Comment by igrekster** [comment]
@martinrotter My apologies -- I didn't anticipate for this PR to require this amount of work.

**Comment by martinrotter** [comment]
Absolutely not a problem, i am hoping to see more Pars from you, thanks.

**Pull request merged**
