### PR TITLE
Add Numix style

### PR DESCRIPTION
**Pull request by varlesh**
- Source icons https://github.com/numixproject/numix-icon-theme
- License GPL-3.0+

### CODE REVIEW

**Comment by martinrotter** [comment]
Wow, will take a log and probably merge. Thank you. :)

**Comment by martinrotter** [comment]
Are you (at least partially) able to keep this icon set up-to-date with main KFaenza RSS Guard icon set when new actions/icons are added? This does not happen too often, sometimes already existing icons are reused.

**Comment by varlesh** [comment]
I'm not sure. But icon theme have source code (SVG-image) and anyone can add need icon.

**Comment by martinrotter** [comment]
Okay.

**Comment by martinrotter** [comment]
Will make some tiny adjustments and this will appear in 2.5.2. Will sync to Bitbucket repo.

**Comment by martinrotter** [comment]
Wow, looks even better than I expected. Impressive. I knew about Numix project. Those icons match RSS Guard nicely.

**Pull request merged**
