### PR TITLE
Enhancing RTL Features: Feed Titles Alignment, Tableview Layout Direction Switching, and Message Marking Read

### PR DESCRIPTION
**Pull request by RachidTagzen**
I encountered issues with my previous commit operation. As a result, I've made 3 fixed commits along with brief explanations for each:

```
1. Prevent message to be marked read when it's selected.
2. Feeds' titles alignment from right to left & vice versa.
3. Ability to switch the entire messages Tableview Layout Direction.
```

<br/><br/>
***
Prevent message to be marked read when it's selected
---
This feature prevents messages from being marked as read automatically when they are selected or clicked on.
It gives users the ability to control when messages are marked as read.

image

<br/><br/>
***
Feeds' titles alignement from right to left & vice versa
---
This feature allows users to choose how the feeds’ titles will be aligned, whether it's from right to left or left to right.

image  |  image

image

<br/><br/>
***
Ability to switch the entire messages Tableview Layout Direction
---
This feature allows users to switch the direction of the entire messages TableView Layout, allowing for a change between right-to-left and left-to-right orientations.

This feature works correctly and perfectly, it handles all the possible cases that are presented in the following truth table :

Truth table

image

### CODE REVIEW

**Comment by martinrotter** [comment]
Lets ignore feature 1 for now.

At this point, there is RTL flag which can be set per-feed and also recursively.

image

Setting RTL into feeds is at this point correctly taken into account when displaying FEED list or ARTICLE list. If category contains some RTL and some NON-RTL feeds then both lists will react appropriately.

Category selected (mixed RTL).
image

Category selected (RTL only)
image

Feed selected (RTL)
image

So from my POV your table above is not factually correct. If feed is marked as RTL, then all its content including the article content is displayed as RTL.
image

Maybe I am missing something but current RSS Guard behavior already de-facto behaves like your above table specifies.

That's for the point 3.

As per point 2 - yes, that subfeature could likely be added but I would maybe prefer it to be feed-specific setting which can also be changed globally via "edit recursive child feeds" feature.

**Comment by RachidTagzen** [comment]
***
Ability to switch the entire messages Tableview Layout Direction
---
Setting RTL into feeds isn't enough. So, I think you forgot to activate this option in the general settings (otherwise the table truth will not be correct):

`Tools -> Settings -> Feeds & articles -> Articles list -> Switch messages tableview direction`

For an RTL feed, the best & comfortable Tableview display is to switch its layout totally to right-to-left, not just set individual columns to right-to-left.
Switching individual columns to right-to-left is only useful in the case when the selected category is mixed.
So, my user experience is prefect using my solution.

This video shows how the feature switchs the Tableview layout direction:
https://www.youtube.com/watch?v=yklb8eFdlbM

<br/><br/>

***
Feeds' titles alignment from right to left & vice versa
---
I think that your suggestion is also good.
So why not use my solution and your suggestion at the same time like this :

- **Global settings :** as a default setting applied to any feed. (Via `Tools -> Settings -> Feeds & articles -> Feeds list`)
- **Category settings :** applied to this category child feeds. (Via `Edit recursive child feeds`)
- **Feed settings :** applied to this feed. (Via `Edit selected items`)

The priority logic order must be like this:
"Feed settings" **overrides** "Category settings" **overrides** "Global settings"

<br/><br/>

**NB:**
Here is my sample database:
[database.zip](https://github.com/martinrotter/rssguard/files/14924638/database.zip)

**Comment by martinrotter** [comment]
OK, so I got your ability to switch entire article list rtl/ltr implemented.

a57a6ab63

**Comment by martinrotter** [comment]
as for remaining feature - rtl feed titles switchable, i will implement later likely

**Pull request closed without merging**
