### PR TITLE
Numix icons fix (application-owncloud and application-ttrss)

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by martinrotter** [comment]
Merging.

**Comment by martinrotter** [comment]
Pls, update this theme - remove unused icons & add new flag icons for new locales. As per base faenza theme.

**Comment by varlesh** [comment]
Ok

**Comment by varlesh** [comment]
Maybe need move icons Numix/*.png to numix folder?

**Comment by martinrotter** [comment]
Just remove the icons with names which are not present in faenza theme, i removed some icons, not needed now + copy new flags into flags folder, you can copy flags from faenza folder.

**Pull request merged**
