### PR TITLE
Add new skins Papirus and Papirus Dark

### PR DESCRIPTION
**Pull request by varlesh**
Autor: varlesh
License: GPL 3

### CODE REVIEW

**Comment by martinrotter** [comment]
So these are actually not skins but icon-packs. Nice. Will you bo able to eventually add additional icons once they will be added by rssguard core mini-kfaenza icon-pack too?

Merging.

**Comment by martinrotter** [comment]
Okay. Code is merged on Github. I will merge to code into the official Bitbucked code repository once I get home.

Thank you. All files, including LICENSE and AUTHOR will be distributed exactly as you posted them. Only change I will made is to rename Papirus and PapirusDark folders to be lowercase.

**Comment by varlesh** [comment]
Maybe add icons later. Ok

**Comment by martinrotter** [comment]
Pls, update this theme - remove unused icons & add new flag icons for new locales. As per base faenza theme.

**Pull request merged**
