### PR TITLE
macOS fixes and changes

### PR DESCRIPTION
**Pull request by phedlund**
- Show "RSS Guard" as the app name in the menu bar.
- Show "RSS Guard" as the app name when hovering over the dock icon.
- Copy Info.plist, PkgInfo, and app icon to the application bundle.
- Remove the executable bit from CHANGELOG

### CODE REVIEW

**Comment by martinrotter** [comment]
So, I see you enabled bundle creation. Does the created bundle work? What command did you use to create the bundle?

**Comment by phedlund** [comment]
A bundle is just a folder. It was already created by $TARGET. I just made sure some needed files ware installed (copied to the bundle). Most importantly Info.plist which every mac app needs.

You had switched away from Qt's automatic way of installing those files so the PR does it "manually".

**Comment by martinrotter** [comment]
What command did you use to create the bundle?

**Comment by martinrotter** [comment]
Because this PR breaks continuous integration on Travis CI, which automatically generates ZIP files containing Mac OS X RSS Guard distribution.

**Comment by martinrotter** [comment]
OK, I fixed travis macosx zipfile generation. You can test. https://transfer.sh/1SwRt/rssguard-3.4.1-d85858e-unix-mac.zip

I will convert it to DMG if you provide the command to create it.

**Comment by phedlund** [comment]
The zip only contains what's inside $PREFIX. It needs to be a zip of 
`    PREFIX = $$quote($$OUT_PWD/$${APP_NAME}.app)`
itself, i.e. RSS Guard.app should be zipped.

**Comment by martinrotter** [comment]
So the ZIP should rather contain the contents of the `RSS GUard.app` directory instead of enclosing directory itself. OK, why not.

I can generate DMG files via `maydeployqt` utility automatically as well, but I had reported that the output DMG file bundle is faulty, can you test it out?

**Comment by martinrotter** [comment]
No, i got it, you actually want the enclosing *.app folder is included in ZIP. Now it is not. OK, fixing.

**Comment by martinrotter** [comment]
Check [this](https://transfer.sh/KvjgA/rssguard-3.4.1-7c79b89-mac.zip).

**Comment by phedlund** [comment]
Yes, looks good. I will test what happens when `macdeployqt` is applied to it. Now it still fails to run due to missing Qt dependencies.

**Comment by phedlund** [comment]
For me locally
`macdeployqt $PREFIX -dmg`
creates a valid dmg. Can you try to run that, and I will verify the output?

**Comment by martinrotter** [comment]
OK.

**Comment by martinrotter** [comment]
Compilation log. https://travis-ci.org/martinrotter/rssguard/jobs/248224739

**Comment by martinrotter** [comment]
https://transfer.sh/R4Jdz/RSS-Guard.dmg

**Comment by phedlund** [comment]
screen shot 2017-06-29 at 6 53 30 am
screen shot 2017-06-29 at 6 53 49 am

Success!

**Pull request merged**
