### PR TITLE
New Feature: user styles

### PR DESCRIPTION
**Pull request by Euro20179**
Addresses #1031.

If there's a better way to inject the css, please let me know, this feels very hacky.

### CODE REVIEW

**Comment by martinrotter** [comment]
Why do you need custom CSS?

Do you need custom CSS only when displaying articles or for all HTML content, including web pages?

**Comment by Euro20179** [comment]
> Do you need custom CSS only when displaying articles or for all HTML content, including web pages?

preferably both, however if I had to chose 1, theming the articles would take priority as they are very plain.

> Why do you need custom CSS?

I need custom css because I like to theme websites i visit often to match my overall system theme.

**Comment by martinrotter** [comment]
Well, what you want is "unofficially" already possible, but only for ARTICLES. For full-blown better solution we would indeed have to add the feature.

Here is solution only for articles
==============

You can use your own "skins" in RSS Guard and CSS theming is part of the skin. Here is sample custom skin which changes all internal web browser texts to "red".

image

First read relevant part of docs:

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#skin

Then, take the attached zip, unpack to your "user-data" folder ("data4"), then go to settings and choose "my-css" skin. Then you can eddit your css in file "html_style.css".

[skins.zip](https://github.com/martinrotter/rssguard/files/12257156/skins.zip)


Your proposed PR is reasonably OK-ish, but in order to merging it, I will rewrite it a bit to get rid of those C++ stdlib classes and use their Qt counterparts (which I prefer in Qt app codebase). Also there is one unaddressed problem. RSS Guard provides 2 distinct internal web browser implementations: one is WebEngine-based which your provided implementation for, the other is simpler text-based "web viewer" which kind of supports some css too and your PR does not provide the same for this backend, although I agree that custom CSS styles for that backend will likely be useless.

I will polish it a bit and think I can merge.

**Comment by martinrotter** [comment]
b5c693ec4

OK, I took your code and polished and did some things better. Now custom style file is loaded from subfolder "web" from user-data folder.

Here is sample log entry which is written when file is detected and loaded:

> time="     0.765" type="debug" -> core: Loading user CSS style file 'C:\Projekty\Moje\build-rssguard-Desktop_Qt_6_3_1_MSVC2017_64bit-Debug\src\rssguard\data4\web\user-styles.css'.

I tested the feature with sample CSS file which turns text to green. Works. Wait for it to compile (20 minutes) and then pls test via "development build". Then let me know here if it works.

https://github.com/martinrotter/rssguard/releases/tag/devbuild

image

**Comment by Euro20179** [comment]
> You can use your own "skins" in RSS Guard and CSS theming is part of the skin. Here is sample custom skin which changes all internal web browser texts to "red".

Oh interesting, should've read the docks more closely.

> but drawback would be that CSS cannot be changed during app lifetime as it is read only once when app starts, but I think that is not a problem for this feature

I agree that this is not an issue.

> OK, I took your code and polished and did some things better

Yeah I wasn't exactly sure where to put everything, so I just left it in a place I knew worked.

> Then let me know here if it works

Works!

**Pull request closed without merging**
